"""add max_devices to licenses

Revision ID: b618a9ccd7d2
Revises: 1bb70cf6f313
Create Date: 2026-06-29 04:41:33.865207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b618a9ccd7d2'
down_revision: Union[str, Sequence[str], None] = '1bb70cf6f313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('max_devices', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licenses', 'max_devices')
    # ### end Alembic commands ###
